/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TheatresRouteImport } from './routes/theatres'
import { Route as ConfirmationBookingIdRouteImport } from './routes/confirmation.$bookingId'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatresRoute = TheatresRouteImport.update({
  id: '/theatres',
  path: '/theatres',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationBookingIdRoute = ConfirmationBookingIdRouteImport.update({
  id: '/confirmation/$bookingId',
  path: '/confirmation/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/theatres': typeof TheatresRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/theatres': typeof TheatresRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies': typeof MoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/theatres': typeof TheatresRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/bookings'
    | '/login'
    | '/offers'
    | '/search'
    | '/theatres'
    | '/confirmation/$bookingId'
    | '/movies/$movieId'
    | '/movies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/bookings'
    | '/login'
    | '/offers'
    | '/search'
    | '/theatres'
    | '/confirmation/$bookingId'
    | '/movies/$movieId'
    | '/movies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/bookings'
    | '/login'
    | '/offers'
    | '/search'
    | '/theatres'
    | '/confirmation/$bookingId'
    | '/movies/$movieId'
    | '/movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  BookingsRoute: typeof BookingsRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  SearchRoute: typeof SearchRoute
  TheatresRoute: typeof TheatresRoute
  ConfirmationBookingIdRoute: typeof ConfirmationBookingIdRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theatres': {
      id: '/theatres'
      path: '/theatres'
      fullPath: '/theatres'
      preLoaderRoute: typeof TheatresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$bookingId': {
      id: '/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/confirmation/$bookingId'
      preLoaderRoute: typeof ConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  BookingsRoute: BookingsRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  SearchRoute: SearchRoute,
  TheatresRoute: TheatresRoute,
  ConfirmationBookingIdRoute: ConfirmationBookingIdRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
